apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-demo-app
  namespace: workloads
  labels:
    app.kubernetes.io/part-of: helm-demo-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: helm
    app.kubernetes.io/component: helm-release
    app.tanzu.vmware.com/release-type: helm
spec:
  interval: 5m
  chart:
    spec:
      chart: java-web-app
      sourceRef:
        kind: HelmRepository
        name: demo-repo
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    autoscaling:
      enabled: true
      minReplicas: 3
    service:
      type: LoadBalancer
    image:
      repository: harbor.vrabbi.cloud/tap/workloads/helm-demo-app-workloads@sha256:3846fd337ff13c3e16c79c824597d8fa8ea71bf804869659b99f2a6610220120

