apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: petclinic
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: petclinic
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    backstage.io/kubernetes-id: petclinic
    app.kubernetes.io/component: run
    carto.run/workload-name: petclinic
spec:
  type: openapi
  description: Manage Vets
  system: default/demo-apps
  owner: default/platform-team
  location:
    apiSpec:
      path: /v3/api-docs
    server:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: petclinic

