apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-name
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: app-name
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: app-name
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.2.8.RELEASE
        conventions.carto.run/applied-conventions: |-
          developer-conventions/debug-convention
          developer-conventions/live-update-convention
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-web
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: harbor.vrabbi.cloud/library/my-code/sample-chatgpt-spring:latest@sha256:71fad39d79fb836ae34ef25183f0443f325f9d850e1d8bb7c020d015db9ef2dc
        developer.conventions/target-containers: workload
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: app-name
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: app-name
        conventions.carto.run/framework: spring-boot
    spec:
      containers:
      - env:
        - name: BPL_DEBUG_ENABLED
          value: "true"
        - name: BPL_DEBUG_PORT
          value: "9005"
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080"
        image: harbor.vrabbi.cloud/tap/workloads/app-name-ns1@sha256:1c909057ed80feab5ffbb0437f42ee82aba20350e8d1645c5aad4fa1ddedfd7e
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

