apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-cart
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: acme-cart
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-cart
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: acme-cart
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: acme-cart
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"acme-cart","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"server"},"name":"acme-cart","namespace":"workloads"},"spec":{"env":[{"name":"CART_PORT","value":"8080"},{"name":"AUTH_MODE","value":"0"},{"name":"REDIS_HOST","value":"cart-redis"},{"name":"REDIS_PORT","value":"6379"},{"name":"REDIS_TLS_ENABLED","value":"false"},{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"cart-redis-pass"}}}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/pipeline":"acme-fitness-generic-test"}},{"name":"ports","value":[{"containerPort":8080,"name":"http","port":80}]}],"source":{"git":{"ref":{"branch":"Azure"},"url":"https://github.com/vrabbi/acme-fitness-store"},"subPath":"apps/acme-cart"}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: acme-cart
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: acme-cart
    spec:
      containers:
      - env:
        - name: CART_PORT
          value: "8080"
        - name: AUTH_MODE
          value: "0"
        - name: REDIS_HOST
          value: cart-redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_TLS_ENABLED
          value: "false"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cart-redis-pass
        image: harbor.vrabbi.cloud/tap/workloads/acme-cart-workloads@sha256:8d4fdab6fda8b3b8cca19742d6d1a31000a5d59294b3f54d1edcf28fcea72070
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: acme-cart
  labels:
    app.kubernetes.io/part-of: acme-cart
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: acme-cart
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: acme-cart
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: acme-cart
  ports:
  - targetPort: 8080
    port: 80
    name: http

