apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-steeltoe
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-steeltoe
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
        developer.apps.tanzu.vmware.com/image-source-digest: harbor.vrabbi.cloud/library/demo-vs-01:latest@sha256:6aa9fcb238dd6052fb000beee80af2d4833d237cb6f720d47050b03123004629
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-steeltoe
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-steeltoe
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: weatherforecast-steeltoe
    spec:
      containers:
      - image: harbor.vrabbi.cloud/tap/workloads/weatherforecast-steeltoe-ns1@sha256:755231f1763ff893ae3af4628496e61df1d8175c7f19a5a948369934a27f0894
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

