apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-demo-workload-01
  description: Sample Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tap-wld01'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
