apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pacman
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: pacman
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    backstage.io/kubernetes-id: pacman
    app.kubernetes.io/component: run
    carto.run/workload-name: pacman
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/vrabbi/js-pacman?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"pacman","apps.tanzu.vmware.com/workload-type":"web","backstage.io/kubernetes-id":"pacman"},"name":"pacman","namespace":"tdp"},"spec":{"params":[{"name":"dockerfile","value":"./Dockerfile"},{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"source":{"git":{"ref":{"branch":"master"},"url":"https://github.com/vrabbi/js-pacman"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: pacman
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        backstage.io/kubernetes-id: pacman
        carto.run/workload-name: pacman
    spec:
      containers:
      - image: harbor.vrabbi.cloud/tap/workloads/pacman-tdp@sha256:1c68ef0491f11e0f2466d87df48f64551cd6479c9a836c89bf60d89980adf511
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

